name = "brandthropic"
type = "javascript"

account_id = "ce91e506d1c2aee6697d276411b3ccc1"
workers_dev = true

# Ensure this line exists to specify the build output directory
pages_build_output_dir = "./dist/assets"  # Change to your actual build folder

compatibility_date = "2025-03-20"
node_version = "18.18.0"


